package com.graduationaldesign.graduation.pojo;

import java.util.ArrayList;
import java.util.List;

public class AcademyExample implements Example {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_academy
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_academy
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_academy
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * 构造查询条件,t_academy
     */
    public AcademyExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * 设置排序字段,t_academy
     *
     * @param orderByClause 排序字段
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * 获取排序字段,t_academy
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * 设置过滤重复数据,t_academy
     *
     * @param distinct 是否过滤重复数据
     */
    @Override
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * 是否过滤重复数据,t_academy
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * 获取当前的查询条件实例,t_academy
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * ,t_academy
     *
     * @param criteria 过滤条件实例
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * ,t_academy
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * 创建一个查询条件,t_academy
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * 内部构建查询条件对象,t_academy
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * 清除查询条件,t_academy
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * InnoDB free: 11264 kB
     * GeneratedCriteria
     * 数据库表：t_academy
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andAcaNameIsNull() {
            addCriterion("aca_name is null");
            return (Criteria) this;
        }

        public Criteria andAcaNameIsNotNull() {
            addCriterion("aca_name is not null");
            return (Criteria) this;
        }

        public Criteria andAcaNameEqualTo(String value) {
            addCriterion("aca_name =", value, "acaName");
            return (Criteria) this;
        }

        public Criteria andAcaNameNotEqualTo(String value) {
            addCriterion("aca_name <>", value, "acaName");
            return (Criteria) this;
        }

        public Criteria andAcaNameGreaterThan(String value) {
            addCriterion("aca_name >", value, "acaName");
            return (Criteria) this;
        }

        public Criteria andAcaNameGreaterThanOrEqualTo(String value) {
            addCriterion("aca_name >=", value, "acaName");
            return (Criteria) this;
        }

        public Criteria andAcaNameLessThan(String value) {
            addCriterion("aca_name <", value, "acaName");
            return (Criteria) this;
        }

        public Criteria andAcaNameLessThanOrEqualTo(String value) {
            addCriterion("aca_name <=", value, "acaName");
            return (Criteria) this;
        }

        public Criteria andAcaNameLike(String value) {
            addCriterion("aca_name like", value, "acaName");
            return (Criteria) this;
        }

        public Criteria andAcaNameNotLike(String value) {
            addCriterion("aca_name not like", value, "acaName");
            return (Criteria) this;
        }

        public Criteria andAcaNameIn(List<String> values) {
            addCriterion("aca_name in", values, "acaName");
            return (Criteria) this;
        }

        public Criteria andAcaNameNotIn(List<String> values) {
            addCriterion("aca_name not in", values, "acaName");
            return (Criteria) this;
        }

        public Criteria andAcaNameBetween(String value1, String value2) {
            addCriterion("aca_name between", value1, value2, "acaName");
            return (Criteria) this;
        }

        public Criteria andAcaNameNotBetween(String value1, String value2) {
            addCriterion("aca_name not between", value1, value2, "acaName");
            return (Criteria) this;
        }

        public Criteria andAcaIntroduceIsNull() {
            addCriterion("aca_introduce is null");
            return (Criteria) this;
        }

        public Criteria andAcaIntroduceIsNotNull() {
            addCriterion("aca_introduce is not null");
            return (Criteria) this;
        }

        public Criteria andAcaIntroduceEqualTo(String value) {
            addCriterion("aca_introduce =", value, "acaIntroduce");
            return (Criteria) this;
        }

        public Criteria andAcaIntroduceNotEqualTo(String value) {
            addCriterion("aca_introduce <>", value, "acaIntroduce");
            return (Criteria) this;
        }

        public Criteria andAcaIntroduceGreaterThan(String value) {
            addCriterion("aca_introduce >", value, "acaIntroduce");
            return (Criteria) this;
        }

        public Criteria andAcaIntroduceGreaterThanOrEqualTo(String value) {
            addCriterion("aca_introduce >=", value, "acaIntroduce");
            return (Criteria) this;
        }

        public Criteria andAcaIntroduceLessThan(String value) {
            addCriterion("aca_introduce <", value, "acaIntroduce");
            return (Criteria) this;
        }

        public Criteria andAcaIntroduceLessThanOrEqualTo(String value) {
            addCriterion("aca_introduce <=", value, "acaIntroduce");
            return (Criteria) this;
        }

        public Criteria andAcaIntroduceLike(String value) {
            addCriterion("aca_introduce like", value, "acaIntroduce");
            return (Criteria) this;
        }

        public Criteria andAcaIntroduceNotLike(String value) {
            addCriterion("aca_introduce not like", value, "acaIntroduce");
            return (Criteria) this;
        }

        public Criteria andAcaIntroduceIn(List<String> values) {
            addCriterion("aca_introduce in", values, "acaIntroduce");
            return (Criteria) this;
        }

        public Criteria andAcaIntroduceNotIn(List<String> values) {
            addCriterion("aca_introduce not in", values, "acaIntroduce");
            return (Criteria) this;
        }

        public Criteria andAcaIntroduceBetween(String value1, String value2) {
            addCriterion("aca_introduce between", value1, value2, "acaIntroduce");
            return (Criteria) this;
        }

        public Criteria andAcaIntroduceNotBetween(String value1, String value2) {
            addCriterion("aca_introduce not between", value1, value2, "acaIntroduce");
            return (Criteria) this;
        }

        public Criteria andJoinEqualLike(String value, String tableName) {
            addCriterion(tableName + " like ", value, tableName);
            return (Criteria) this;
        }

        public Criteria andJoinEqualTo(Object value, String tableName) {
            addCriterion(tableName + " = ", value, tableName);
            return (Criteria) this;
        }
    }

    /**
     * 类注释
     * Criteria
     * 数据库表：t_academy
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * InnoDB free: 11264 kB
     * Criterion
     * 数据库表：t_academy
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}