package com.graduationaldesign.graduation.pojo;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import java.io.Serializable;


@JsonIgnoreProperties(value = {"handler"})
public class Admin implements Serializable {
    /**
     * 
     * 表字段 : admin.id
     */
    private Integer id;

    /**
     * 
     * 表字段 : admin.userName
     */
    private String username;

    /**
     * 
     * 表字段 : admin.power
     */
    private String power;

    /**
     * 
     * 表字段 : admin.describe_
     */
    private String describe;

    /**
     * 
     * 表字段 : admin.telphone
     */
    private String telphone;

    /**
     * 
     * 表字段 : admin.email
     */
    private String email;

    /**
     * 
     * 表字段 : admin.time
     */
    private String time;

    /**
     * 
     * 表字段 : admin.passwd
     */
    private String passwd;

    /**
     * 1是正常，2是冻结
     * 表字段 : admin.state
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table admin
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取  字段:admin.id
     *
     * @return admin.id, 
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置  字段:admin.id
     *
     * @param id the value for admin.id, 
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取  字段:admin.userName
     *
     * @return admin.userName, 
     */
    public String getUsername() {
        return username;
    }

    /**
     * 设置  字段:admin.userName
     *
     * @param username the value for admin.userName, 
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * 获取  字段:admin.power
     *
     * @return admin.power, 
     */
    public String getPower() {
        return power;
    }

    /**
     * 设置  字段:admin.power
     *
     * @param power the value for admin.power, 
     */
    public void setPower(String power) {
        this.power = power == null ? null : power.trim();
    }

    /**
     * 获取  字段:admin.describe_
     *
     * @return admin.describe_, 
     */
    public String getDescribe() {
        return describe;
    }

    /**
     * 设置  字段:admin.describe_
     *
     * @param describe the value for admin.describe_, 
     */
    public void setDescribe(String describe) {
        this.describe = describe == null ? null : describe.trim();
    }

    /**
     * 获取  字段:admin.telphone
     *
     * @return admin.telphone, 
     */
    public String getTelphone() {
        return telphone;
    }

    /**
     * 设置  字段:admin.telphone
     *
     * @param telphone the value for admin.telphone, 
     */
    public void setTelphone(String telphone) {
        this.telphone = telphone == null ? null : telphone.trim();
    }

    /**
     * 获取  字段:admin.email
     *
     * @return admin.email, 
     */
    public String getEmail() {
        return email;
    }

    /**
     * 设置  字段:admin.email
     *
     * @param email the value for admin.email, 
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * 获取  字段:admin.time
     *
     * @return admin.time, 
     */
    public String getTime() {
        return time;
    }

    /**
     * 设置  字段:admin.time
     *
     * @param time the value for admin.time, 
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }

    /**
     * 获取  字段:admin.passwd
     *
     * @return admin.passwd, 
     */
    public String getPasswd() {
        return passwd;
    }

    /**
     * 设置  字段:admin.passwd
     *
     * @param passwd the value for admin.passwd, 
     */
    public void setPasswd(String passwd) {
        this.passwd = passwd == null ? null : passwd.trim();
    }

    /**
     * 获取 1是正常，2是冻结 字段:admin.state
     *
     * @return admin.state, 1是正常，2是冻结
     */
    public Integer getState() {
        return state;
    }

    /**
     * 设置 1是正常，2是冻结 字段:admin.state
     *
     * @param state the value for admin.state, 1是正常，2是冻结
     */
    public void setState(Integer state) {
        this.state = state;
    }
}