package com.graduationaldesign.graduation.pojo;

import cn.afterturn.easypoi.excel.annotation.Excel;
import cn.hutool.core.date.DateUtil;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.graduationaldesign.graduation.pojo.helper.Column;
import com.graduationaldesign.graduation.pojo.helper.MyPrimaryKey;
import com.graduationaldesign.graduation.pojo.helper.Table;
import lombok.Data;

import java.io.Serializable;
import java.util.Date;

@Data
@JsonIgnoreProperties(value = {"handler"})
@Table(value = "t_apply")
public class Apply implements Serializable {

    /**
     * 表字段 : t_apply.id
     */
    @MyPrimaryKey
    @Excel(name = "申请ID*", orderNum = "1")
    @Column(columnName = "id", viewName = "applyId")
    private Integer id;

    /**
     * 申请导师id，外键
     * 表字段 : t_apply.apply_tea_id
     */
    @Excel(name = "申请导师id", orderNum = "1")
    @Column(columnName = "apply_tea_id", joinPojo = "Teacher")
    private String applyTeaId;

    /**
     * 处理状态，1是待处理，2是已处理
     * 表字段 : t_apply.apply_state
     */
    @Excel(name = "处理状态(默认是1)", orderNum = "1")
    @Column(columnName = "apply_state")
    private Integer applyState;

    /**
     * 关联学生id
     * 表字段 : t_apply.apply_stu_id
     */
    @Excel(name = "关联学生id", orderNum = "1")
    @Column(columnName = "apply_stu_id", joinPojo = "Student")
    private String applyStuId;

    /**
     * 关联课题
     * 表字段 : t_apply.apply_sub_id
     */
    @Excel(name = "关联课题id", orderNum = "1")
    @Column(columnName = "apply_sub_id", joinPojo = "Subject")
    private String applySubId;

    /**
     * 申请时间
     * 表字段 : t_apply.apply_time
     */
    @Excel(name = "申请时间", orderNum = "1")
    @Column(columnName = "apply_time")
    private Date applyTime;

    /**
     * 处理时间
     * 表字段 : t_apply.apply_reply_time
     */
    @Excel(name = "处理时间", orderNum = "1")
    @Column(columnName = "apply_reply_time")
    private Date applyReplyTime;

    /**
     * 申请内容
     * 表字段 : t_apply.apply_content
     */
    @Excel(name = "申请内容", orderNum = "1")
    @Column(columnName = "apply_content")
    private String applyContent;

    /**
     * 申请理由
     * 表字段 : t_apply.apply_reason
     */
    @Excel(name = "申请理由", orderNum = "1")
    @Column(columnName = "apply_reason")
    private String applyReason;

    /**
     * 处理反馈
     * 表字段 : t_apply.apply_reply
     */
    @Excel(name = "处理反馈", orderNum = "1")
    @Column(columnName = "apply_reply")
    private String applyReply;

    private Student student;

    private Subject subject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_apply
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取  字段:t_apply.id
     *
     * @return t_apply.id,
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置  字段:t_apply.id
     *
     * @param id the value for t_apply.id,
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取 申请导师id，外键 字段:t_apply.apply_tea_id
     *
     * @return t_apply.apply_tea_id, 申请导师id，外键
     */
    public String getApplyTeaId() {
        return applyTeaId;
    }

    /**
     * 设置 申请导师id，外键 字段:t_apply.apply_tea_id
     *
     * @param applyTeaId the value for t_apply.apply_tea_id, 申请导师id，外键
     */
    public void setApplyTeaId(String applyTeaId) {
        this.applyTeaId = applyTeaId == null ? null : applyTeaId.trim();
    }

    /**
     * 获取 处理状态，1是待处理，2是已处理 字段:t_apply.apply_state
     *
     * @return t_apply.apply_state, 处理状态，1是待处理，2是已处理
     */
    public Integer getApplyState() {
        return applyState;
    }

    /**
     * 设置 处理状态，1是待处理，2是已处理 字段:t_apply.apply_state
     *
     * @param applyState the value for t_apply.apply_state, 处理状态，1是待处理，2是已处理
     */
    public void setApplyState(Integer applyState) {
        this.applyState = applyState;
    }

    /**
     * 获取 关联学生id 字段:t_apply.apply_stu_id
     *
     * @return t_apply.apply_stu_id, 关联学生id
     */
    public String getApplyStuId() {
        return applyStuId;
    }

    /**
     * 设置 关联学生id 字段:t_apply.apply_stu_id
     *
     * @param applyStuId the value for t_apply.apply_stu_id, 关联学生id
     */
    public void setApplyStuId(String applyStuId) {
        this.applyStuId = applyStuId == null ? null : applyStuId.trim();
    }

    /**
     * 获取 关联课题 字段:t_apply.apply_sub_id
     *
     * @return t_apply.apply_sub_id, 关联课题
     */
    public String getApplySubId() {
        return applySubId;
    }

    /**
     * 设置 关联课题 字段:t_apply.apply_sub_id
     *
     * @param applySubId the value for t_apply.apply_sub_id, 关联课题
     */
    public void setApplySubId(String applySubId) {
        this.applySubId = applySubId == null ? null : applySubId.trim();
    }

    /**
     * 获取 申请时间 字段:t_apply.apply_time
     *
     * @return t_apply.apply_time, 申请时间
     */
    public String getApplyTime() {
        return DateUtil.formatDateTime(applyTime);
    }

    /**
     * 设置 申请时间 字段:t_apply.apply_time
     *
     * @param applyTime the value for t_apply.apply_time, 申请时间
     */
    public void setApplyTime(Date applyTime) {
        this.applyTime = applyTime;
    }

    /**
     * 获取 处理时间 字段:t_apply.apply_reply_time
     *
     * @return t_apply.apply_reply_time, 处理时间
     */
    public String getApplyReplyTime() {
        return DateUtil.formatDateTime(applyReplyTime);
    }

    /**
     * 设置 处理时间 字段:t_apply.apply_reply_time
     *
     * @param applyReplyTime the value for t_apply.apply_reply_time, 处理时间
     */
    public void setApplyReplyTime(Date applyReplyTime) {
        this.applyReplyTime = applyReplyTime;
    }

    /**
     * 获取 申请内容 字段:t_apply.apply_content
     *
     * @return t_apply.apply_content, 申请内容
     */
    public String getApplyContent() {
        return applyContent;
    }

    /**
     * 设置 申请内容 字段:t_apply.apply_content
     *
     * @param applyContent the value for t_apply.apply_content, 申请内容
     */
    public void setApplyContent(String applyContent) {
        this.applyContent = applyContent == null ? null : applyContent.trim();
    }

    /**
     * 获取 申请理由 字段:t_apply.apply_reason
     *
     * @return t_apply.apply_reason, 申请理由
     */
    public String getApplyReason() {
        return applyReason;
    }

    /**
     * 设置 申请理由 字段:t_apply.apply_reason
     *
     * @param applyReason the value for t_apply.apply_reason, 申请理由
     */
    public void setApplyReason(String applyReason) {
        this.applyReason = applyReason == null ? null : applyReason.trim();
    }

    /**
     * 获取 处理反馈 字段:t_apply.apply_reply
     *
     * @return t_apply.apply_reply, 处理反馈
     */
    public String getApplyReply() {
        return applyReply;
    }

    /**
     * 设置 处理反馈 字段:t_apply.apply_reply
     *
     * @param applyReply the value for t_apply.apply_reply, 处理反馈
     */
    public void setApplyReply(String applyReply) {
        this.applyReply = applyReply == null ? null : applyReply.trim();
    }

    @JsonIgnore
    public Student getStudent() {
        return student;
    }

    @JsonGetter(value = "student")
    public Student getStudentDetail() {//自定的方法
        return student;
    }

    public void setStudent(Student student) {
        this.student = student;
    }

    @JsonIgnore
    public Subject getSubject() {
        return subject;
    }

    @JsonGetter(value = "subject")
    public Subject getSubjectDetail() {//自定的方法
        return subject;
    }

    public void setSubject(Subject subject) {
        this.subject = subject;
    }
}