package com.graduationaldesign.graduation.pojo;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import java.io.Serializable;

@JsonIgnoreProperties(value = {"handler"})
public class Comment implements Serializable {
    /**
     * 
     * 表字段 : comment_.id
     */
    private Integer id;

    /**
     * 
     * 表字段 : comment_.did
     */
    private Integer did;

    /**
     * 
     * 表字段 : comment_.time
     */
    private String time;

    /**
     * 
     * 表字段 : comment_.reply
     */
    private String reply;

    /**
     * 
     * 表字段 : comment_.uid
     */
    private Integer uid;

    /**
     * 
     * 表字段 : comment_.content
     */
    private String content;

    private User user;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table comment_
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取  字段:comment_.id
     *
     * @return comment_.id, 
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置  字段:comment_.id
     *
     * @param id the value for comment_.id, 
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取  字段:comment_.did
     *
     * @return comment_.did, 
     */
    public Integer getDid() {
        return did;
    }

    /**
     * 设置  字段:comment_.did
     *
     * @param did the value for comment_.did, 
     */
    public void setDid(Integer did) {
        this.did = did;
    }

    /**
     * 获取  字段:comment_.time
     *
     * @return comment_.time, 
     */
    public String getTime() {
        return time;
    }

    /**
     * 设置  字段:comment_.time
     *
     * @param time the value for comment_.time, 
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }

    /**
     * 获取  字段:comment_.reply
     *
     * @return comment_.reply, 
     */
    public String getReply() {
        return reply;
    }

    /**
     * 设置  字段:comment_.reply
     *
     * @param reply the value for comment_.reply, 
     */
    public void setReply(String reply) {
        this.reply = reply == null ? null : reply.trim();
    }

    /**
     * 获取  字段:comment_.uid
     *
     * @return comment_.uid, 
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * 设置  字段:comment_.uid
     *
     * @param uid the value for comment_.uid, 
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * 获取  字段:comment_.content
     *
     * @return comment_.content, 
     */
    public String getContent() {
        return content;
    }

    /**
     * 设置  字段:comment_.content
     *
     * @param content the value for comment_.content, 
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user=user;
    }
}