package com.graduationaldesign.graduation.pojo;

import cn.hutool.core.date.DateUtil;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.io.Serializable;
import java.util.Date;
import lombok.Data;

@Data
@JsonIgnoreProperties(value = {"handler"})
public class DesignShow implements Serializable {

    /**
     * 表字段 : t_designshow.id
     */
    private Integer id;

    /**
     * 表字段 : t_designshow.sub_id
     */
    private String subId;

    /**
     * 附件
     * 表字段 : t_designshow.show_file
     */
    private String showFile;

    /**
     * 上传时间
     * 表字段 : t_designshow.show_time
     */
    private Date showTime;

    /**
     * 展示内容
     * 表字段 : t_designshow.show_content
     */
    private String showContent;

    private Subject subject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_designshow
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取  字段:t_designshow.id
     *
     * @return t_designshow.id,
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置  字段:t_designshow.id
     *
     * @param id the value for t_designshow.id,
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取  字段:t_designshow.sub_id
     *
     * @return t_designshow.sub_id,
     */
    public String getSubId() {
        return subId;
    }

    /**
     * 设置  字段:t_designshow.sub_id
     *
     * @param subId the value for t_designshow.sub_id,
     */
    public void setSubId(String subId) {
        this.subId = subId == null ? null : subId.trim();
    }

    /**
     * 获取 附件 字段:t_designshow.show_file
     *
     * @return t_designshow.show_file, 附件
     */
    public String getShowFile() {
        return showFile;
    }

    /**
     * 设置 附件 字段:t_designshow.show_file
     *
     * @param showFile the value for t_designshow.show_file, 附件
     */
    public void setShowFile(String showFile) {
        this.showFile = showFile == null ? null : showFile.trim();
    }

    /**
     * 获取 上传时间 字段:t_designshow.show_time
     *
     * @return t_designshow.show_time, 上传时间
     */
    public String getShowTime() {
        return DateUtil.formatDateTime(showTime);
    }

    /**
     * 设置 上传时间 字段:t_designshow.show_time
     *
     * @param showTime the value for t_designshow.show_time, 上传时间
     */
    public void setShowTime(Date showTime) {
        this.showTime = showTime;
    }

    /**
     * 获取 展示内容 字段:t_designshow.show_content
     *
     * @return t_designshow.show_content, 展示内容
     */
    public String getShowContent() {
        return showContent;
    }

    /**
     * 设置 展示内容 字段:t_designshow.show_content
     *
     * @param showContent the value for t_designshow.show_content, 展示内容
     */
    public void setShowContent(String showContent) {
        this.showContent = showContent == null ? null : showContent.trim();
    }

    @JsonIgnore
    public Subject getSubject() {
        return subject;
    }

    @JsonGetter(value = "subject")
    public Subject getSubjectDetail() {//自定的方法
        return subject;
    }

    public void setSubject(Subject subject) {
        this.subject = subject;
    }
}