package com.graduationaldesign.graduation.pojo;

import cn.afterturn.easypoi.excel.annotation.Excel;
import cn.hutool.core.date.DateUtil;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.graduationaldesign.graduation.pojo.helper.MyPrimaryKey;
import java.io.Serializable;
import java.util.Date;
import lombok.Data;

@Data
@JsonIgnoreProperties(value = {"handler"})
public class DesignShow implements Serializable {

    /**
     * 表字段 : t_designshow.id
     */
    @MyPrimaryKey
    @Excel(name = "设计展示id", orderNum = "1")
    private Integer id;

    /**
     * 表字段 : t_designshow.show_sub_id
     */
    @Excel(name = "课题id", orderNum = "1")
    private String showSubId;

    /**
     * 附件
     * 表字段 : t_designshow.show_file
     */
    @Excel(name = "附件路径", orderNum = "1")
    private String showFile;

    /**
     * 上传时间
     * 表字段 : t_designshow.show_time
     */
    @Excel(name = "设计展示时间", orderNum = "1")
    private Date showTime;

    /**
     * 展示内容
     * 表字段 : t_designshow.show_content
     */
    @Excel(name = "展示内容", orderNum = "1")
    private String showContent;

    private Subject subject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_designshow
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取  字段:t_designshow.id
     *
     * @return t_designshow.id,
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置  字段:t_designshow.id
     *
     * @param id the value for t_designshow.id,
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取  字段:t_designshow.show_sub_id
     *
     * @return t_designshow.show_sub_id,
     */
    public String getShowSubId() {
        return showSubId;
    }

    /**
     * 设置  字段:t_designshow.show_sub_id
     *
     * @param showSubId the value for t_designshow.show_sub_id,
     */
    public void setShowSubId(String showSubId) {
        this.showSubId = showSubId == null ? null : showSubId.trim();
    }

    /**
     * 获取 附件 字段:t_designshow.show_file
     *
     * @return t_designshow.show_file, 附件
     */
    public String getShowFile() {
        return showFile;
    }

    /**
     * 设置 附件 字段:t_designshow.show_file
     *
     * @param showFile the value for t_designshow.show_file, 附件
     */
    public void setShowFile(String showFile) {
        this.showFile = showFile == null ? null : showFile.trim();
    }

    /**
     * 获取 上传时间 字段:t_designshow.show_time
     *
     * @return t_designshow.show_time, 上传时间
     */
    public String getShowTime() {
        return DateUtil.formatDateTime(showTime);
    }

    /**
     * 设置 上传时间 字段:t_designshow.show_time
     *
     * @param showTime the value for t_designshow.show_time, 上传时间
     */
    public void setShowTime(Date showTime) {
        this.showTime = showTime;
    }

    /**
     * 获取 展示内容 字段:t_designshow.show_content
     *
     * @return t_designshow.show_content, 展示内容
     */
    public String getShowContent() {
        return showContent;
    }

    /**
     * 设置 展示内容 字段:t_designshow.show_content
     *
     * @param showContent the value for t_designshow.show_content, 展示内容
     */
    public void setShowContent(String showContent) {
        this.showContent = showContent == null ? null : showContent.trim();
    }

    @JsonIgnore
    public Subject getSubject() {
        return subject;
    }

    @JsonGetter(value = "subject")
    public Subject getSubjectDetail() {//自定的方法
        return subject;
    }

    public void setSubject(Subject subject) {
        this.subject = subject;
    }
}