package com.graduationaldesign.graduation.pojo;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import java.io.Serializable;
import java.util.List;

@JsonIgnoreProperties(value = {"handler"})
public class Diary implements Serializable {
    /**
     * 
     * 表字段 : diary.Did
     */
    private Integer did;

    /**
     * 
     * 表字段 : diary.title
     */
    private String title;

    /**
     * 
     * 表字段 : diary.classify
     */
    private String classify;

    /**
     * 
     * 表字段 : diary.dTime
     */
    private String dtime;

    /**
     * 
     * 表字段 : diary.Uid
     */
    private Integer uid;

    /**
     * 
     * 表字段 : diary.image
     */
    private String image;

    /**
     * 
     * 表字段 : diary.likenum
     */
    private Integer likenum;

    /**
     * 
     * 表字段 : diary.province
     */
    private String province;

    /**
     * 
     * 表字段 : diary.city
     */
    private String city;

    /**
     * 
     * 表字段 : diary.countryRegion
     */
    private String countryregion;

    /**
     * 
     * 表字段 : diary.monthTime
     */
    private Integer monthtime;

    /**
     * 
     * 表字段 : diary.totalTime
     */
    private Integer totaltime;

    /**
     * 
     * 表字段 : diary.keyLandscape
     */
    private String keylandscape;

    /**
     * 
     * 表字段 : diary.content
     */
    private String content;

    /**
     * 
     * 表字段 : diary.content2
     */
    private String content2;

    private User user;

    private List<Comment> comments;

    private List<DiaryPhoto> diaryPhotos;

    private List<Like> likes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table diary
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取  字段:diary.Did
     *
     * @return diary.Did, 
     */
    public Integer getDid() {
        return did;
    }

    /**
     * 设置  字段:diary.Did
     *
     * @param did the value for diary.Did, 
     */
    public void setDid(Integer did) {
        this.did = did;
    }

    /**
     * 获取  字段:diary.title
     *
     * @return diary.title, 
     */
    public String getTitle() {
        return title;
    }

    /**
     * 设置  字段:diary.title
     *
     * @param title the value for diary.title, 
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * 获取  字段:diary.classify
     *
     * @return diary.classify, 
     */
    public String getClassify() {
        return classify;
    }

    /**
     * 设置  字段:diary.classify
     *
     * @param classify the value for diary.classify, 
     */
    public void setClassify(String classify) {
        this.classify = classify == null ? null : classify.trim();
    }

    /**
     * 获取  字段:diary.dTime
     *
     * @return diary.dTime, 
     */
    public String getDtime() {
        return dtime;
    }

    /**
     * 设置  字段:diary.dTime
     *
     * @param dtime the value for diary.dTime, 
     */
    public void setDtime(String dtime) {
        this.dtime = dtime == null ? null : dtime.trim();
    }

    /**
     * 获取  字段:diary.Uid
     *
     * @return diary.Uid, 
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * 设置  字段:diary.Uid
     *
     * @param uid the value for diary.Uid, 
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * 获取  字段:diary.image
     *
     * @return diary.image, 
     */
    public String getImage() {
        return image;
    }

    /**
     * 设置  字段:diary.image
     *
     * @param image the value for diary.image, 
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * 获取  字段:diary.likenum
     *
     * @return diary.likenum, 
     */
    public Integer getLikenum() {
        return likenum;
    }

    /**
     * 设置  字段:diary.likenum
     *
     * @param likenum the value for diary.likenum, 
     */
    public void setLikenum(Integer likenum) {
        this.likenum = likenum;
    }

    /**
     * 获取  字段:diary.province
     *
     * @return diary.province, 
     */
    public String getProvince() {
        return province;
    }

    /**
     * 设置  字段:diary.province
     *
     * @param province the value for diary.province, 
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * 获取  字段:diary.city
     *
     * @return diary.city, 
     */
    public String getCity() {
        return city;
    }

    /**
     * 设置  字段:diary.city
     *
     * @param city the value for diary.city, 
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * 获取  字段:diary.countryRegion
     *
     * @return diary.countryRegion, 
     */
    public String getCountryregion() {
        return countryregion;
    }

    /**
     * 设置  字段:diary.countryRegion
     *
     * @param countryregion the value for diary.countryRegion, 
     */
    public void setCountryregion(String countryregion) {
        this.countryregion = countryregion == null ? null : countryregion.trim();
    }

    /**
     * 获取  字段:diary.monthTime
     *
     * @return diary.monthTime, 
     */
    public Integer getMonthtime() {
        return monthtime;
    }

    /**
     * 设置  字段:diary.monthTime
     *
     * @param monthtime the value for diary.monthTime, 
     */
    public void setMonthtime(Integer monthtime) {
        this.monthtime = monthtime;
    }

    /**
     * 获取  字段:diary.totalTime
     *
     * @return diary.totalTime, 
     */
    public Integer getTotaltime() {
        return totaltime;
    }

    /**
     * 设置  字段:diary.totalTime
     *
     * @param totaltime the value for diary.totalTime, 
     */
    public void setTotaltime(Integer totaltime) {
        this.totaltime = totaltime;
    }

    /**
     * 获取  字段:diary.keyLandscape
     *
     * @return diary.keyLandscape, 
     */
    public String getKeylandscape() {
        return keylandscape;
    }

    /**
     * 设置  字段:diary.keyLandscape
     *
     * @param keylandscape the value for diary.keyLandscape, 
     */
    public void setKeylandscape(String keylandscape) {
        this.keylandscape = keylandscape == null ? null : keylandscape.trim();
    }

    /**
     * 获取  字段:diary.content
     *
     * @return diary.content, 
     */
    public String getContent() {
        return content;
    }

    /**
     * 设置  字段:diary.content
     *
     * @param content the value for diary.content, 
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * 获取  字段:diary.content2
     *
     * @return diary.content2, 
     */
    public String getContent2() {
        return content2;
    }

    /**
     * 设置  字段:diary.content2
     *
     * @param content2 the value for diary.content2, 
     */
    public void setContent2(String content2) {
        this.content2 = content2 == null ? null : content2.trim();
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user=user;
    }

    public List<Comment> getComments() {
        return comments;
    }

    public void setComments(List<Comment> comments) {
        this.comments=comments;
    }

    public List<DiaryPhoto> getDiaryPhotos() {
        return diaryPhotos;
    }

    public void setDiaryPhotos(List<DiaryPhoto> diaryPhotos) {
        this.diaryPhotos=diaryPhotos;
    }

    public List<Like> getLikes() {
        return likes;
    }

    public void setLikes(List<Like> likes) {
        this.likes=likes;
    }
}