package com.graduationaldesign.graduation.pojo;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import java.io.Serializable;


@JsonIgnoreProperties(value = {"handler"})
public class DraftsPhoto implements Serializable {
    /**
     * 
     * 表字段 : dphoto.id
     */
    private Integer id;

    /**
     * 
     * 表字段 : dphoto.image
     */
    private String image;

    /**
     * 
     * 表字段 : dphoto.did
     */
    private Integer did;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dphoto
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取  字段:dphoto.id
     *
     * @return dphoto.id, 
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置  字段:dphoto.id
     *
     * @param id the value for dphoto.id, 
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取  字段:dphoto.image
     *
     * @return dphoto.image, 
     */
    public String getImage() {
        return image;
    }

    /**
     * 设置  字段:dphoto.image
     *
     * @param image the value for dphoto.image, 
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * 获取  字段:dphoto.did
     *
     * @return dphoto.did, 
     */
    public Integer getDid() {
        return did;
    }

    /**
     * 设置  字段:dphoto.did
     *
     * @param did the value for dphoto.did, 
     */
    public void setDid(Integer did) {
        this.did = did;
    }
}