package com.graduationaldesign.graduation.pojo;

import java.io.Serializable;
import java.util.Date;

public class GoodGraduation implements Serializable {
    /**
     * 
     * 表字段 : t_goodgraduation.id
     */
    private Integer id;

    /**
     * 外键课题id
     * 表字段 : t_goodgraduation.sub_id
     */
    private String subId;

    /**
     * 评定时间
     * 表字段 : t_goodgraduation.good_time
     */
    private Date goodTime;

    /**
     * 评定理由
     * 表字段 : t_goodgraduation.good_reason
     */
    private String goodReason;

    private Subject subject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_goodgraduation
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取  字段:t_goodgraduation.id
     *
     * @return t_goodgraduation.id, 
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置  字段:t_goodgraduation.id
     *
     * @param id the value for t_goodgraduation.id, 
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取 外键课题id 字段:t_goodgraduation.sub_id
     *
     * @return t_goodgraduation.sub_id, 外键课题id
     */
    public String getSubId() {
        return subId;
    }

    /**
     * 设置 外键课题id 字段:t_goodgraduation.sub_id
     *
     * @param subId the value for t_goodgraduation.sub_id, 外键课题id
     */
    public void setSubId(String subId) {
        this.subId = subId == null ? null : subId.trim();
    }

    /**
     * 获取 评定时间 字段:t_goodgraduation.good_time
     *
     * @return t_goodgraduation.good_time, 评定时间
     */
    public Date getGoodTime() {
        return goodTime;
    }

    /**
     * 设置 评定时间 字段:t_goodgraduation.good_time
     *
     * @param goodTime the value for t_goodgraduation.good_time, 评定时间
     */
    public void setGoodTime(Date goodTime) {
        this.goodTime = goodTime;
    }

    /**
     * 获取 评定理由 字段:t_goodgraduation.good_reason
     *
     * @return t_goodgraduation.good_reason, 评定理由
     */
    public String getGoodReason() {
        return goodReason;
    }

    /**
     * 设置 评定理由 字段:t_goodgraduation.good_reason
     *
     * @param goodReason the value for t_goodgraduation.good_reason, 评定理由
     */
    public void setGoodReason(String goodReason) {
        this.goodReason = goodReason == null ? null : goodReason.trim();
    }

    public Subject getSubject() {
        return subject;
    }

    public void setSubject(Subject subject) {
        this.subject=subject;
    }
}