package com.graduationaldesign.graduation.pojo;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import java.io.Serializable;


@JsonIgnoreProperties(value = {"handler"})
public class Message implements Serializable {
    /**
     * 
     * 表字段 : message.id
     */
    private Integer id;

    /**
     * 
     * 表字段 : message.content
     */
    private String content;

    /**
     * 
     * 表字段 : message.reply
     */
    private String reply;

    /**
     * 
     * 表字段 : message.dTime
     */
    private String dtime;

    /**
     * 
     * 表字段 : message.Uid
     */
    private Integer uid;

    private User user;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table message
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取  字段:message.id
     *
     * @return message.id, 
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置  字段:message.id
     *
     * @param id the value for message.id, 
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取  字段:message.content
     *
     * @return message.content, 
     */
    public String getContent() {
        return content;
    }

    /**
     * 设置  字段:message.content
     *
     * @param content the value for message.content, 
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * 获取  字段:message.reply
     *
     * @return message.reply, 
     */
    public String getReply() {
        return reply;
    }

    /**
     * 设置  字段:message.reply
     *
     * @param reply the value for message.reply, 
     */
    public void setReply(String reply) {
        this.reply = reply == null ? null : reply.trim();
    }

    /**
     * 获取  字段:message.dTime
     *
     * @return message.dTime, 
     */
    public String getDtime() {
        return dtime;
    }

    /**
     * 设置  字段:message.dTime
     *
     * @param dtime the value for message.dTime, 
     */
    public void setDtime(String dtime) {
        this.dtime = dtime == null ? null : dtime.trim();
    }

    /**
     * 获取  字段:message.Uid
     *
     * @return message.Uid, 
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * 设置  字段:message.Uid
     *
     * @param uid the value for message.Uid, 
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user=user;
    }
}