package com.graduationaldesign.graduation.pojo;

import cn.hutool.core.date.DateUtil;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.graduationaldesign.graduation.pojo.helper.MyPrimaryKey;
import java.io.Serializable;
import java.util.Date;
import lombok.Data;

@Data
@JsonIgnoreProperties(value = {"handler"})
public class Progress implements Serializable {

    /**
     * 表字段 : t_progress.id
     */
    @MyPrimaryKey
    private Integer id;

    /**
     * 课题id，外键课题表id
     * 表字段 : t_progress.progress_sub_id
     */
    private String progressSubId;

    /**
     * 问题发表时间
     * 表字段 : t_progress.prog_content_time
     */
    private Date progContentTime;

    /**
     * 导师回复时间
     * 表字段 : t_progress.prog_reply_time
     */
    private Date progReplyTime;

    /**
     * 问题内容
     * 表字段 : t_progress.prog_content
     */
    private String progContent;

    /**
     * 导师回复内容
     * 表字段 : t_progress.prog_reply
     */
    private String progReply;

    private Subject subject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_progress
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取  字段:t_progress.id
     *
     * @return t_progress.id,
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置  字段:t_progress.id
     *
     * @param id the value for t_progress.id,
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取 课题id，外键课题表id 字段:t_progress.progress_sub_id
     *
     * @return t_progress.progress_sub_id, 课题id，外键课题表id
     */
    public String getProgressSubId() {
        return progressSubId;
    }

    /**
     * 设置 课题id，外键课题表id 字段:t_progress.progress_sub_id
     *
     * @param progressSubId the value for t_progress.progress_sub_id, 课题id，外键课题表id
     */
    public void setProgressSubId(String progressSubId) {
        this.progressSubId = progressSubId == null ? null : progressSubId.trim();
    }

    /**
     * 获取 问题发表时间 字段:t_progress.prog_content_time
     *
     * @return t_progress.prog_content_time, 问题发表时间
     */
    public String getProgContentTime() {
        return DateUtil.formatDateTime(progContentTime);
    }

    /**
     * 设置 问题发表时间 字段:t_progress.prog_content_time
     *
     * @param progContentTime the value for t_progress.prog_content_time, 问题发表时间
     */
    public void setProgContentTime(Date progContentTime) {
        this.progContentTime = progContentTime;
    }

    /**
     * 获取 导师回复时间 字段:t_progress.prog_reply_time
     *
     * @return t_progress.prog_reply_time, 导师回复时间
     */
    public String getProgReplyTime() {
        return DateUtil.formatDateTime(progReplyTime);
    }

    /**
     * 设置 导师回复时间 字段:t_progress.prog_reply_time
     *
     * @param progReplyTime the value for t_progress.prog_reply_time, 导师回复时间
     */
    public void setProgReplyTime(Date progReplyTime) {
        this.progReplyTime = progReplyTime;
    }

    /**
     * 获取 问题内容 字段:t_progress.prog_content
     *
     * @return t_progress.prog_content, 问题内容
     */
    public String getProgContent() {
        return progContent;
    }

    /**
     * 设置 问题内容 字段:t_progress.prog_content
     *
     * @param progContent the value for t_progress.prog_content, 问题内容
     */
    public void setProgContent(String progContent) {
        this.progContent = progContent == null ? null : progContent.trim();
    }

    /**
     * 获取 导师回复内容 字段:t_progress.prog_reply
     *
     * @return t_progress.prog_reply, 导师回复内容
     */
    public String getProgReply() {
        return progReply;
    }

    /**
     * 设置 导师回复内容 字段:t_progress.prog_reply
     *
     * @param progReply the value for t_progress.prog_reply, 导师回复内容
     */
    public void setProgReply(String progReply) {
        this.progReply = progReply == null ? null : progReply.trim();
    }

    @JsonIgnore
    public Subject getSubject() {
        return subject;
    }

    @JsonGetter(value = "subject")
    public Subject getSubjectDetail() {//自定的方法
        return subject;
    }

    public void setSubject(Subject subject) {
        this.subject = subject;
    }
}