package com.graduationaldesign.graduation.pojo;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.graduationaldesign.graduation.pojo.helper.MyPrimaryKey;
import lombok.Data;

import java.io.Serializable;
import java.util.Date;

@Data
@JsonIgnoreProperties(value = {"handler"})
public class Report implements Serializable {

    /**
     * 课题id，外键对课题表id
     * 表字段 : t_report.report_sub_id
     */
    private String reportSubId;

    /**
     * 报告类型，1是开题报告，2是论文定稿
     * 表字段 : t_report.report_type
     */
    private Integer reportType;

    /**
     * 表字段 : t_report.id
     */
    @MyPrimaryKey
    private Integer id;

    /**
     * 状态：1是未提交，2是已提交，3是延期提交，4是通过，5是驳回待修改，6是已修改
     * 表字段 : t_report.report_state
     */
    private Integer reportState;

    /**
     * 报告提交时间
     * 表字段 : t_report.report_subtime
     */
    private Date reportSubtime;

    /**
     * 版本信息，默认是0
     * 表字段 : t_report.report_version
     */
    private Float reportVersion;

    /**
     * 报告附件
     * 表字段 : t_report.report_file
     */
    private String reportFile;

    /**
     * 报告模板
     * 表字段 : t_report.report_temp
     */
    private String reportTemp;

    /**
     * 报告内容（使用富文本编辑）
     * 表字段 : t_report.report_content
     */
    private String reportContent;

    /**
     * 学生提交反馈信息
     * 表字段 : t_report.stu_message
     */
    private String stuMessage;

    /**
     * 导师意见
     * 表字段 : t_report.tea_suggestion
     */
    private String teaSuggestion;

    private Subject subject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_report
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    public Report(String subId, Integer reportType, Integer reportState) {
        this.reportSubId = subId;
        this.reportType = reportType;
        this.reportState = reportState;
    }

    public Report() {
    }

    public Report(String subId, Integer reportType) {
        this.reportSubId = subId;
        this.reportType = reportType;
    }

    /**
     * 获取 课题id，外键对课题表id 字段:t_report.report_sub_id
     *
     * @return t_report.report_sub_id, 课题id，外键对课题表id
     */
    public String getReportSubId() {
        return reportSubId;
    }

    /**
     * 设置 课题id，外键对课题表id 字段:t_report.report_sub_id
     *
     * @param reportSubId the value for t_report.report_sub_id, 课题id，外键对课题表id
     */
    public void setReportSubId(String reportSubId) {
        this.reportSubId = reportSubId == null ? null : reportSubId.trim();
    }

    /**
     * 获取 报告类型，1是开题报告，2是论文定稿 字段:t_report.report_type
     *
     * @return t_report.report_type, 报告类型，1是开题报告，2是论文定稿
     */
    public Integer getReportType() {
        return reportType;
    }

    /**
     * 设置 报告类型，1是开题报告，2是论文定稿 字段:t_report.report_type
     *
     * @param reportType the value for t_report.report_type, 报告类型，1是开题报告，2是论文定稿
     */
    public void setReportType(Integer reportType) {
        this.reportType = reportType;
    }

    /**
     * 获取  字段:t_report.id
     *
     * @return t_report.id,
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置  字段:t_report.id
     *
     * @param id the value for t_report.id,
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取 状态：1是未提交，2是已提交，3是延期提交，4是通过，5是驳回待修改，6是已修改 字段:t_report.report_state
     *
     * @return t_report.report_state, 状态：1是未提交，2是已提交，3是延期提交，4是通过，5是驳回待修改，6是已修改
     */
    public Integer getReportState() {
        return reportState;
    }

    /**
     * 设置 状态：1是未提交，2是已提交，3是延期提交，4是通过，5是驳回待修改，6是已修改 字段:t_report.report_state
     *
     * @param reportState the value for t_report.report_state, 状态：1是未提交，2是已提交，3是延期提交，4是通过，5是驳回待修改，6是已修改
     */
    public void setReportState(Integer reportState) {
        this.reportState = reportState;
    }

    /**
     * 获取 报告提交时间 字段:t_report.report_subtime
     *
     * @return t_report.report_subtime, 报告提交时间
     */
    public Date getReportSubtime() {
        return reportSubtime;
    }

    /**
     * 设置 报告提交时间 字段:t_report.report_subtime
     *
     * @param reportSubtime the value for t_report.report_subtime, 报告提交时间
     */
    public void setReportSubtime(Date reportSubtime) {
        this.reportSubtime = reportSubtime;
    }

    /**
     * 获取 版本信息，默认是0 字段:t_report.report_version
     *
     * @return t_report.report_version, 版本信息，默认是0
     */
    public Float getReportVersion() {
        return reportVersion;
    }

    /**
     * 设置 版本信息，默认是0 字段:t_report.report_version
     *
     * @param reportVersion the value for t_report.report_version, 版本信息，默认是0
     */
    public void setReportVersion(Float reportVersion) {
        this.reportVersion = reportVersion;
    }

    /**
     * 获取 报告附件 字段:t_report.report_file
     *
     * @return t_report.report_file, 报告附件
     */
    public String getReportFile() {
        return reportFile;
    }

    /**
     * 设置 报告附件 字段:t_report.report_file
     *
     * @param reportFile the value for t_report.report_file, 报告附件
     */
    public void setReportFile(String reportFile) {
        this.reportFile = reportFile == null ? null : reportFile.trim();
    }

    /**
     * 获取 报告模板 字段:t_report.report_temp
     *
     * @return t_report.report_temp, 报告模板
     */
    public String getReportTemp() {
        return reportTemp;
    }

    /**
     * 设置 报告模板 字段:t_report.report_temp
     *
     * @param reportTemp the value for t_report.report_temp, 报告模板
     */
    public void setReportTemp(String reportTemp) {
        this.reportTemp = reportTemp == null ? null : reportTemp.trim();
    }

    /**
     * 获取 报告内容（使用富文本编辑） 字段:t_report.report_content
     *
     * @return t_report.report_content, 报告内容（使用富文本编辑）
     */
    public String getReportContent() {
        return reportContent;
    }

    /**
     * 设置 报告内容（使用富文本编辑） 字段:t_report.report_content
     *
     * @param reportContent the value for t_report.report_content, 报告内容（使用富文本编辑）
     */
    public void setReportContent(String reportContent) {
        this.reportContent = reportContent == null ? null : reportContent.trim();
    }

    /**
     * 获取 学生提交反馈信息 字段:t_report.stu_message
     *
     * @return t_report.stu_message, 学生提交反馈信息
     */
    public String getStuMessage() {
        return stuMessage;
    }

    /**
     * 设置 学生提交反馈信息 字段:t_report.stu_message
     *
     * @param stuMessage the value for t_report.stu_message, 学生提交反馈信息
     */
    public void setStuMessage(String stuMessage) {
        this.stuMessage = stuMessage == null ? null : stuMessage.trim();
    }

    /**
     * 获取 导师意见 字段:t_report.tea_suggestion
     *
     * @return t_report.tea_suggestion, 导师意见
     */
    public String getTeaSuggestion() {
        return teaSuggestion;
    }

    /**
     * 设置 导师意见 字段:t_report.tea_suggestion
     *
     * @param teaSuggestion the value for t_report.tea_suggestion, 导师意见
     */
    public void setTeaSuggestion(String teaSuggestion) {
        this.teaSuggestion = teaSuggestion == null ? null : teaSuggestion.trim();
    }

    @JsonIgnore
    public Subject getSubject() {
        return subject;
    }

    @JsonGetter(value = "subject")
    public Subject getSubjectDetail() {//自定的方法
        return subject;
    }

    public void setSubject(Subject subject) {
        this.subject = subject;
    }
}