package com.graduationaldesign.graduation.pojo;

import java.io.Serializable;

public class RolePermission implements Serializable {
    /**
     * 
     * 表字段 : t_role_permission.id
     */
    private Long id;

    /**
     * 角色id，外键
     * 表字段 : t_role_permission.role_id
     */
    private Long roleId;

    /**
     * 权限id，外键
     * 表字段 : t_role_permission.per_id
     */
    private Long perId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_role_permission
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取  字段:t_role_permission.id
     *
     * @return t_role_permission.id, 
     */
    public Long getId() {
        return id;
    }

    /**
     * 设置  字段:t_role_permission.id
     *
     * @param id the value for t_role_permission.id, 
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 获取 角色id，外键 字段:t_role_permission.role_id
     *
     * @return t_role_permission.role_id, 角色id，外键
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * 设置 角色id，外键 字段:t_role_permission.role_id
     *
     * @param roleId the value for t_role_permission.role_id, 角色id，外键
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * 获取 权限id，外键 字段:t_role_permission.per_id
     *
     * @return t_role_permission.per_id, 权限id，外键
     */
    public Long getPerId() {
        return perId;
    }

    /**
     * 设置 权限id，外键 字段:t_role_permission.per_id
     *
     * @param perId the value for t_role_permission.per_id, 权限id，外键
     */
    public void setPerId(Long perId) {
        this.perId = perId;
    }
}