package com.graduationaldesign.graduation.pojo;

import com.graduationaldesign.graduation.pojo.helper.Column;
import com.graduationaldesign.graduation.pojo.helper.MyPrimaryKey;
import com.graduationaldesign.graduation.pojo.helper.Table;
import lombok.Data;

import java.io.Serializable;

@Data
@Table(value = "t_role_permission")
public class RolePermission implements Serializable {

    /**
     * 表字段 : t_role_permission.id
     */
    @MyPrimaryKey
    @Column(columnName = "id")
    private Long id;

    /**
     * 角色id，外键
     * 表字段 : t_role_permission.role_id
     */
    @Column(columnName = "role_id", joinPojo = "Role")
    private Long roleId;

    /**
     * 权限id，外键
     * 表字段 : t_role_permission.per_id
     */
    @Column(columnName = "per_id", joinPojo = "Permission")
    private Long perId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_role_permission
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取  字段:t_role_permission.id
     *
     * @return t_role_permission.id,
     */
    public Long getId() {
        return id;
    }

    /**
     * 设置  字段:t_role_permission.id
     *
     * @param id the value for t_role_permission.id,
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 获取 角色id，外键 字段:t_role_permission.role_id
     *
     * @return t_role_permission.role_id, 角色id，外键
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * 设置 角色id，外键 字段:t_role_permission.role_id
     *
     * @param roleId the value for t_role_permission.role_id, 角色id，外键
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * 获取 权限id，外键 字段:t_role_permission.per_id
     *
     * @return t_role_permission.per_id, 权限id，外键
     */
    public Long getPerId() {
        return perId;
    }

    /**
     * 设置 权限id，外键 字段:t_role_permission.per_id
     *
     * @param perId the value for t_role_permission.per_id, 权限id，外键
     */
    public void setPerId(Long perId) {
        this.perId = perId;
    }
}