package com.graduationaldesign.graduation.pojo;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import java.io.Serializable;
import java.util.Set;


@JsonIgnoreProperties(value = {"handler"})
public class User implements Serializable {

    /**
     * 用户对应的角色集合
     */
    private Set<Role> roles;
    /**
     * 
     * 表字段 : user.id
     */
    private Integer id;

    /**
     * 
     * 表字段 : user.UserName
     */
    private String userName;

    /**
     * 
     * 表字段 : user.passwd
     */
    private String passwd;

    /**
     * 
     * 表字段 : user.sex
     */
    private String sex;

    /**
     * 
     * 表字段 : user.Email
     */
    private String email;

    /**
     * 
     * 表字段 : user.IndividualResume
     */
    private String individualResume;

    /**
     * 
     * 表字段 : user.image
     */
    private String image;

    /**
     * 
     * 表字段 : user.site
     */
    private String site;

    /**
     * 1是正常，2是被禁用
     * 表字段 : user.state
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取  字段:user.id
     *
     * @return user.id, 
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置  字段:user.id
     *
     * @param id the value for user.id, 
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取  字段:user.UserName
     *
     * @return user.UserName, 
     */
    public String getUserName() {
        return userName;
    }

    /**
     * 设置  字段:user.UserName
     *
     * @param userName the value for user.UserName, 
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * 获取  字段:user.passwd
     *
     * @return user.passwd, 
     */
    public String getPasswd() {
        return passwd;
    }

    /**
     * 设置  字段:user.passwd
     *
     * @param passwd the value for user.passwd, 
     */
    public void setPasswd(String passwd) {
        this.passwd = passwd == null ? null : passwd.trim();
    }

    /**
     * 获取  字段:user.sex
     *
     * @return user.sex, 
     */
    public String getSex() {
        return sex;
    }

    /**
     * 设置  字段:user.sex
     *
     * @param sex the value for user.sex, 
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * 获取  字段:user.Email
     *
     * @return user.Email, 
     */
    public String getEmail() {
        return email;
    }

    /**
     * 设置  字段:user.Email
     *
     * @param email the value for user.Email, 
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * 获取  字段:user.IndividualResume
     *
     * @return user.IndividualResume, 
     */
    public String getIndividualResume() {
        return individualResume;
    }

    /**
     * 设置  字段:user.IndividualResume
     *
     * @param individualResume the value for user.IndividualResume, 
     */
    public void setIndividualResume(String individualResume) {
        this.individualResume = individualResume == null ? null : individualResume.trim();
    }

    /**
     * 获取  字段:user.image
     *
     * @return user.image, 
     */
    public String getImage() {
        return image;
    }

    /**
     * 设置  字段:user.image
     *
     * @param image the value for user.image, 
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * 获取  字段:user.site
     *
     * @return user.site, 
     */
    public String getSite() {
        return site;
    }

    /**
     * 设置  字段:user.site
     *
     * @param site the value for user.site, 
     */
    public void setSite(String site) {
        this.site = site == null ? null : site.trim();
    }

    /**
     * 获取 1是正常，2是被禁用 字段:user.state
     *
     * @return user.state, 1是正常，2是被禁用
     */
    public Integer getState() {
        return state;
    }

    /**
     * 设置 1是正常，2是被禁用 字段:user.state
     *
     * @param state the value for user.state, 1是正常，2是被禁用
     */
    public void setState(Integer state) {
        this.state = state;
    }

    public Set<Role> getRoles() {
        return roles;
    }

    public void setRoles(Set<Role> roles) {
        this.roles = roles;
    }

    public User(Integer id, String userName, String passwd,Set<Role> roles) {
        this.roles = roles;
        this.id = id;
        this.userName = userName;
        this.passwd = passwd;
    }
}